yarnPath: .yarn/releases/yarn-4.9.2.cjs

enableGlobalCache: false
checksumBehavior: ignore

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
    - win32
